#!/bin/bash

#Take the two strings as arguments
firstString=$1
secondString=$2

if [[ $# == 0 ]]
then
	echo "Please Pass Two Strings To Compare  as Arguments"
	exit
fi

if [[ $firstString == $secondString ]]
then
	echo "Strings are Equal"
else
	echo "Strings are not Equal"
fi

# Check if firstString variable is a substring of a string.
key="Servers use Linux"
if [[ $key == *"$firstString"* ]];then
	echo "Yes, firstString variable is the substring of key"
else
	echo "No, firstString variable is not the substring of key"
fi