#!/bin/sh

# Program to check Greatest among Three Numbers
# Nested If else
echo "Enter First Number"
read a
echo "Enter Second Number"
read b
echo "Enter Third Number"
read c

if [[ $a -gt $b && $a -gt $c ]]
then echo "$a is Greater"
elif [ $b -gt $c ]
then echo "$b is Greater"
else echo "$c is Greater"
fi
