#!/bin/sh

# Objective: Small Program, Which has Predefined Username and Password

echo "Welcome To School Management System \n Enter Your Details"
echo "Enter Your Username"
read userName
echo "Enter Your Password"
read password

if [ $password  == "Home" -a $userName == "Student" ]
then echo -n "You Are Logged In"
else
	echo -n "Check Your Details"
fi

