#!/bin/sh

#Calculator Command Line Based

echo "Enter First Number"
read a
echo "Enter Second Number"
read b
# Addition
sum=`expr $a + $b`
echo "$a+$b: $sum"
# Subtraction
sub=`expr $a - $b`
echo "$a-$b: $sub"
# Division
div=`expr $a / $b`
echo "$a/$b: $div"
# Multiplication
mul=`expr $a \* $b`
echo "$a*$b: $mul"
# Modulus
modulo=`expr $a % $b`
echo "$a%$b: $modulo"

# Using if-else in shell scripts
if [ $a -eq  $b ]
then 
	echo "$a is equal to $b"
else
	echo "$a is not equal to $b"
fi

